preload = ~/nixos-config/home/hyprland/wallpapers/wall.jpg
#wallpaper = eDP-1,~/nixos-config/home/hyprland/wallpapers/wall.jpg
wallpaper = ,~/nixos-config/home/hyprland/wallpapers/wall.jpg
splash = false
